<?php

namespace Database\Seeders;

use App\Models\Siswa;
use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class SiswaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        //
        $dataSiswa = [
            [
                'nama_lengkap' => 'Aisyah Putri',
                'tanggal_lahir' => '2019-05-12',
                'tempat_lahir' => 'Jakarta',
                'usia' => 5,
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'status_keluarga' => 'Anak Kandung',
                'alamat' => 'LIMUS PRATAMA REGENCY, JALAN CENDANA VI BLOK F12 NO. 8',
                'riwayat_penyakit' => 'Tidak Ada',
                'nama_ayah' => 'Ahmad',
                'pekerjaan_ayah' => 'Guru',
                'hp_ayah' => '081234567001',
                'nama_ibu' => 'Siti',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'hp_ibu' => '081234567011',
                'kelas_id' => 1,
                'latitude' => '-6.361845140639322',
                'longitude' => '106.96985586550002',
            ],
            [
                'nama_lengkap' => 'Budi Santoso',
                'tanggal_lahir' => '2018-10-30',
                'tempat_lahir' => 'Bandung',
                'usia' => 6,
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'status_keluarga' => 'Anak Kandung',
                'alamat' => 'Kota Wisata Cluster West Covina Blok SG 2 No 11',
                'riwayat_penyakit' => 'Asma',
                'nama_ayah' => 'Slamet',
                'pekerjaan_ayah' => 'Petani',
                'hp_ayah' => '081234567002',
                'nama_ibu' => 'Dewi',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'hp_ibu' => '081234567012',
                'kelas_id' => 1,
                'latitude' => '-6.354619726723088',
                'longitude' => '106.9599739397214',
            ],
            [
                'nama_lengkap' => 'Chandra Wijaya',
                'tanggal_lahir' => '2019-03-15',
                'tempat_lahir' => 'Surabaya',
                'usia' => 5,
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Kristen',
                'status_keluarga' => 'Anak Kandung',
                'alamat' => 'Taman Rahayu Regency B5 No.90 Rt.003/008',
                'riwayat_penyakit' => 'Tidak Ada',
                'nama_ayah' => 'Sudarno',
                'pekerjaan_ayah' => 'Dokter',
                'hp_ayah' => '081234567003',
                'nama_ibu' => 'Lina',
                'pekerjaan_ibu' => 'Perawat',
                'hp_ibu' => '081234567013',
                'kelas_id' => 2,
                'latitude' => '-6.363805226014001',
                'longitude' => '106.99530487498268',
            ],
            [
                'nama_lengkap' => 'Dina Maharani',
                'tanggal_lahir' => '2018-12-22',
                'tempat_lahir' => 'Malang',
                'usia' => 6,
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Hindu',
                'status_keluarga' => 'Anak Kandung',
                'alamat' => 'Limus Pratama Regency, Jl. Pekalongan V blok H3 No.38',
                'riwayat_penyakit' => 'Flu',
                'nama_ayah' => 'Sutrisno',
                'pekerjaan_ayah' => 'Pegawai Negeri',
                'hp_ayah' => '081234567004',
                'nama_ibu' => 'Desi',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'hp_ibu' => '081234567014',
                'kelas_id' => 2,
                'latitude' => '-6.3589191126688975',
                'longitude' => '106.96971673311526',
            ],
            [
                'nama_lengkap' => 'Eka Pratiwi',
                'tanggal_lahir' => '2019-01-25',
                'tempat_lahir' => 'Semarang',
                'usia' => 5,
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'status_keluarga' => 'Anak Kandung',
                'alamat' => 'PERUMAHAN LIMUS PRATAMA REGENCY, JL. SUMENEP 2 BLOK B1/36',
                'riwayat_penyakit' => 'Tidak Ada',
                'nama_ayah' => 'Bambang',
                'pekerjaan_ayah' => 'Wiraswasta',
                'hp_ayah' => '081234567005',
                'nama_ibu' => 'Tuti',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'hp_ibu' => '081234567015',
                'kelas_id' => 1,
                'latitude' => '-6.361238119123295',
                'longitude' => '106.97345820936687',
            ],
            [
                'nama_lengkap' => 'Fahri Alamsyah',
                'tanggal_lahir' => '2018-06-10',
                'tempat_lahir' => 'Yogyakarta',
                'usia' => 6,
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'status_keluarga' => 'Anak Kandung',
                'alamat' => 'Limus pratama regensi, Blok C5 no 21, RT 08 RW 06 Cileungsi - Bogor ',
                'riwayat_penyakit' => 'Demam',
                'nama_ayah' => 'Rizal',
                'pekerjaan_ayah' => 'Polisi',
                'hp_ayah' => '081234567006',
                'nama_ibu' => 'Amelia',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'hp_ibu' => '081234567016',
                'kelas_id' => 2,
                'latitude' => '-6.361821738198089',
                'longitude' => '106.97075281585434',
            ],

            [
                'nama_lengkap' => 'Gina Oktaviani',
                'tanggal_lahir' => '2019-09-11',
                'tempat_lahir' => 'Medan',
                'usia' => 5,
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Budha',
                'status_keluarga' => 'Anak Kandung',
                'alamat' => 'METLAND CILEUNGSI SEKTOR 6, CLUSTER AIMARA BLOK FF1/28 CIPENJO CILEUNGSI KAB.BOGOR',
                'riwayat_penyakit' => 'Tidak Ada',
                'nama_ayah' => 'Joni',
                'pekerjaan_ayah' => 'Pedagang',
                'hp_ayah' => '081234567007',
                'nama_ibu' => 'Lina',
                'pekerjaan_ibu' => 'Perawat',
                'hp_ibu' => '081234567017',
                'kelas_id' => 2,
                'latitude' => '-6.385254351910688',
                'longitude' => '106.99493899091823',
            ],
            [
                'nama_lengkap' => 'Hadi Prasetyo',
                'tanggal_lahir' => '2018-11-05',
                'tempat_lahir' => 'Bandung',
                'usia' => 6,
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'status_keluarga' => 'Anak Kandung',
                'alamat' => 'Kota wisata cluster Monaco blok W4 no. 57',
                'riwayat_penyakit' => 'Tidak Ada',
                'nama_ayah' => 'Rudi',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'hp_ayah' => '081234567008',
                'nama_ibu' => 'Yanti',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'hp_ibu' => '081234567018',
                'kelas_id' => 1,
                'latitude' => '-6.3882206538004125',
                'longitude' => '106.94964529932854',
            ],
            [
                'nama_lengkap' => 'Indah Nuraini',
                'tanggal_lahir' => '2019-04-17',
                'tempat_lahir' => 'Solo',
                'usia' => 5,
                'jenis_kelamin' => 'Perempuan',
                'agama' => 'Islam',
                'status_keluarga' => 'Anak Kandung',
                'alamat' => 'Metland Cileungsi Cluster Lily Blok DC3 16',
                'riwayat_penyakit' => 'Tidak Ada',
                'nama_ayah' => 'Anton',
                'pekerjaan_ayah' => 'Wiraswasta',
                'hp_ayah' => '081234567009',
                'nama_ibu' => 'Rina',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'hp_ibu' => '081234567019',
                'kelas_id' => 1,
                'latitude' => '-6.3886232620777665',
                'longitude' => '106.98805787034087',
            ],
            [
                'nama_lengkap' => 'Fauzan Fuad',
                'tanggal_lahir' => '2018-08-22',
                'tempat_lahir' => 'Bogor',
                'usia' => 6,
                'jenis_kelamin' => 'Laki-laki',
                'agama' => 'Islam',
                'status_keluarga' => 'Anak Kandung',
                'alamat' => 'Cikarang Selatan, Jl. Raya Cikarang No. 45',
                'riwayat_penyakit' => 'Tidak Ada',
                'nama_ayah' => 'Sukardi',
                'pekerjaan_ayah' => 'Karyawan Swasta',
                'hp_ayah' => '081234567010',
                'nama_ibu' => 'Sari',
                'pekerjaan_ibu' => 'Ibu Rumah Tangga',
                'hp_ibu' => '081234567020',
                'kelas_id' => 2,
                'latitude' => '-6.236396622861856',
                'longitude' => '106.9754083335064',
            ],
        ];

        foreach ($dataSiswa as $index => $siswa) {
            $user = User::factory()->create([
                'name' => $siswa['nama_lengkap'],
                'email' => 'siswa' . ($index + 1) . '@mail.com',
                'password' => Hash::make('siswapassword'),
                'role' => 'siswa', // opsional jika kamu pakai field ini
            ]);

            Siswa::create(array_merge($siswa, [
                'user_id' => $user->id,
            ]));
        }
    }
}
